export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const ADD_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_CART_FAILURE = "ADD_TO_CART_FAILURE"
export const ADD_CART_SUCCESS = "ADD_TO_CART_SUCCESS"


export const DELETE_CART_REQUEST = "DELETE_TO_CART_REQUEST"
export const DELETE_CART_FAILURE = "DELETE_TO_CART_FAILURE"
export const DELETE_CART_SUCCESS = "DELETE_TO_CART_SUCCESS"

export const GET_CART_REQUEST = "GET_TO_CART_REQUEST"
export const GET_CART_FAILURE = "GET_TO_CART_FAILURE"
export const GET_CART_SUCCESS = "GET_TO_CART_SUCCESS"



export const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAILURE = "GET_WISHLIST_FAILURE";

export const ADD_WISHLIST_REQUEST = "ADD_WISHLIST_REQUEST";
export const ADD_WISHLIST_SUCCESS = "ADD_WISHLIST_SUCCESS";
export const ADD_WISHLIST_FAILURE = "ADD_WISHLIST_FAILURE";

export const DELETE_WISHLIST_REQUEST = "DELETE_WISHLIST_REQUEST";
export const DELETE_WISHLIST_SUCCESS = "DELETE_WISHLIST_SUCCESS";
export const DELETE_WISHLIST_FAILURE = "DELETE_WISHLIST_FAILURE";

